version: "3.8"

networks:
  wp_net:
    driver: overlay
    attachable: true

secrets:
  mariadb_root_password:
    external: true

volumes:
  wp_data:
    external: true
  mariadb_data:
    external: true

services:
  db:
    image: mariadb:11.4
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wp
      - MYSQL_PASSWORD_FILE=/run/secrets/mariadb_root_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mariadb_root_password
    secrets:
      - mariadb_root_password
    networks:
      - wp_net
    volumes:
      - mariadb_data:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager   # lub usuń constraint, jeśli ma działać na dowolnym nodzie
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
      rollback_config:
        order: stop-first
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot --password=$$(cat /run/secrets/mariadb_root_password) || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s

  wordpress:
    image: wordpress:6.6-fpm
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wp
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/mariadb_root_password
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - db
    secrets:
      - mariadb_root_password
    networks:
      - wp_net
    volumes:
      - wp_data:/var/www/html
    deploy:
      mode: replicated
      replicas: 2               # skalowanie aplikacji
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        order: stop-first
    healthcheck:
      test: ["CMD-SHELL", "php -v >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s

  nginx:
    image: nginx:1.27-alpine
    networks:
      - wp_net
    ports:
      - "80:80"
    depends_on:
      - wordpress
    volumes:
      # Prosty vhost proxy do php-fpm w kontenerze 'wordpress'
      - wp_data:/var/www/html:ro
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker    # przykład: front na workerach
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
